#include "mappacklib.h"

int mapgroupbuff[6][8]={
    { 0 , 1 , 2 , 3 , 4 , 5 , -1, -1 },
    { 6 , 7 , 8 , 9 , 10, 11, -1, -1 },
    { 12, 13, 14, 15, 16, 17, 18, -1 },
    { 19, 20, 21, -1, -1, -1, -1, -1 },
    { 22, 23, 24, 25, 26, -1, -1, -1 },
    { 27, 28, 29, 30, -1, -1, -1, -1 },
};

uint8_t *mapliblist[31] = {
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,
    (uint8_t *)map_Outside_A1data,
    (uint8_t *)map_Outside_A2data,
    (uint8_t *)map_Outside_A3data,
    (uint8_t *)map_Outside_A4data,
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,     
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,
    (uint8_t *)nullptr,
};


/*
uint8_t *mapliblist[31] = {
    (uint8_t *)map_Dungeon_A1data,
    (uint8_t *)map_Dungeon_A2data,
    (uint8_t *)map_Dungeon_A4data,
    (uint8_t *)map_Dungeon_A5data,
    (uint8_t *)map_Dungeon_Bdata,
    (uint8_t *)map_Dungeon_Cdata,
    (uint8_t *)map_Inside_A1data,
    (uint8_t *)map_Inside_A2data,
    (uint8_t *)map_Inside_A4data,
    (uint8_t *)map_Inside_A5data,
    (uint8_t *)map_Inside_Bdata,
    (uint8_t *)map_Inside_Cdata,
    (uint8_t *)map_Outside_A1data,
    (uint8_t *)map_Outside_A2data,
    (uint8_t *)map_Outside_A3data,
    (uint8_t *)map_Outside_A4data,
    (uint8_t *)map_Outside_A5data,
    (uint8_t *)map_Outside_Bdata,
    (uint8_t *)map_Outside_Cdata,
    (uint8_t *)map_SF_Inside_A4data,
    (uint8_t *)map_SF_Inside_Bdata,
    (uint8_t *)map_SF_Inside_Cdata,
    (uint8_t *)map_SF_Outside_A3data,
    (uint8_t *)map_SF_Outside_A4data,
    (uint8_t *)map_SF_Outside_A5data,
    (uint8_t *)map_SF_Outside_Bdata,
    (uint8_t *)map_SF_Outside_Cdata,
    (uint8_t *)map_World_A1data,
    (uint8_t *)map_World_A2data,
    (uint8_t *)map_World_Bdata,
    (uint8_t *)map_World_Cdata,
};
*/
